name: mura_app
description: ಮುದ್ದುರಾಮನ ಮನಸು - Simple Verses, Profound Truths

environment:
 flutter: "3.19.3"

dependencies:
 flutter:
  sdk: flutter
 google_fonts: ^6.1.0
 provider: ^6.1.1
 shared_preferences: ^2.2.2
 share_plus: ^9.0.0
 url_launcher: ^6.2.4
 flutter_staggered_animations: ^1.1.1

dev_dependencies:
 flutter_test:
  sdk: flutter
 flutter_lints: ^3.0.0

publish_to: 'none'
version: 1.0.0+1
